# Generated by Django 4.0.4 on 2022-04-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0002_alter_task_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='executor_list',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
