# Generated by Django 4.0.4 on 2022-04-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0003_task_executor_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor_list',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
